apiVersion: v1
kind: Secret
metadata:
  name: tonghai-secrets
  namespace: tonghai-dev
type: Opaque
data:
  # Base64 encoded values for local testing only
  # postgres://crm_user:crm_password@postgres:5432/crm_db
  DATABASE_URL: "cG9zdGdyZXM6Ly9jcm1fdXNlcjpjcm1fcGFzc3dvcmRAcG9zdGdyZXM6NTQzMi9jcm1fZGI="
  
  # your_jwt_secret_here
  JWT_SECRET: "eW91cl9qd3Rfc2VjcmV0X2hlcmU="
  
  # crm_user
  POSTGRES_USER: "Y3JtX3VzZXI="
  
  # crm_password
  POSTGRES_PASSWORD: "Y3JtX3Bhc3N3b3Jk"
  
  # crm_db
  POSTGRES_DB: "Y3JtX2Ri"
