/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AIChatSheet: typeof import('./src/components/AIChatSheet.vue')['default']
    AIDriftBall: typeof import('./src/components/AIDriftBall.vue')['default']
    BaseLayout: typeof import('./src/components/BaseLayout.vue')['default']
    NutButton: typeof import('nutui-uniapp/components/button/button.vue')['default']
    NutCell: typeof import('nutui-uniapp/components/cell/cell.vue')['default']
    NutCollapse: typeof import('nutui-uniapp/components/collapse/collapse.vue')['default']
    NutCollapseItem: typeof import('nutui-uniapp/components/collapseitem/collapseitem.vue')['default']
    NutForm: typeof import('nutui-uniapp/components/form/form.vue')['default']
    NutFormItem: typeof import('nutui-uniapp/components/formitem/formitem.vue')['default']
    NutInput: typeof import('nutui-uniapp/components/input/input.vue')['default']
    NutNoticebar: typeof import('nutui-uniapp/components/noticebar/noticebar.vue')['default']
    NutPopup: typeof import('nutui-uniapp/components/popup/popup.vue')['default']
    NutUploader: typeof import('nutui-uniapp/components/uploader/uploader.vue')['default']
    WizardTimeline: typeof import('./src/components/WizardTimeline.vue')['default']
  }
}
